### PR TITLE
Fix number formatting in excel files

### LINKED ISSUE #292: Numbers in excel files get converted to floats
Screenshot from 2021-03-02 10-40-02
Screenshot from 2021-03-02 10-39-57

### PR DESCRIPTION
**Pull request by zmedelis**
Closes #292

### CODE REVIEW

**Review by rokasramas — CHANGES_REQUESTED** [review]
Sorry, I missed the message in slack yesterday. The `data.entities.data-files` ns should be kept as is, this is not an anti-pattern in clojure, and there are many instances where this kind of structure is used in the repository. The main idea is that we lose hierarchy when namespaces are at the same level, in this instance, `row-selection` contains only specific utility functions, and is not as important as `data-files` ns.

**Comment by zmedelis** [comment]
>The `data.entities.data-files` ns should be kept as is

Rolled back the NS name change and moved the coercion code to its own NS.

File: api/test/api/datomic_fixtures.clj [hunk 1]
```diff
@@ -1,15 +1,15 @@
 (ns api.datomic-fixtures
-  (:require [api.config]
-            [data.datomic.impl]
-            [data.entities.amr]
-            [data.entities.data-files]
-            [data.entities.dictionary]
-            [data.entities.document-plan]
-            [data.entities.reader-model]
-            [data.entities.results]
+  (:require api.config
```
Comment (rokasramas) [inline api/test/api/datomic_fixtures.clj:2]: dropping [ ] is unusual, maybe this was unintended?

**Review by rokasramas — CHANGES_REQUESTED** [review]

**Review by rokasramas — APPROVED** [review]
